services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fab\Formule\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Fab\Formule\Controller\:
    public: true
    tags: ['controller.service_arguments']

  Fab\Formule\Slot\ValuesSanitizer:
    tags:
      - name: event.listener
        event: Fab\Formule\Event\BeforeProcessValuesEvent
        method: sanitize
